---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: consumer
  labels:
    app: consumer
    version: v1
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
  replicas: 3
  selector:
    matchLabels:
      app: consumer
  template:
    metadata:
      name: consumer
      labels:
        app: consumer
        version: v1
    spec:
      containers:
        - name: consumer
          image: mostela/rc_consumer
          imagePullPolicy: Always
          livenessProbe:
            httpGet:
              port: 8000
              path: /healthcheck
          ports:
            - containerPort: 8000
              name: http
              protocol: TCP
          env:
            - name: REMOTE_CONFIG_URL
              value: http://producer-control-service.producer-control.svc.cluster.local:8080/keyrotation
---
apiVersion: v1
kind: Service
metadata:
  name: consumer
  labels:
    app: consumer
    version: v1
spec:
  type: LoadBalancer
  selector:
    app: consumer
    version: v1
  ports:
    - port: 80
      targetPort: 8000
      protocol: TCP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-complex
  labels:
    app: complex-example
    version: v1
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - backend:
              service:
                name: consumer
                port:
                  number: 80
            pathType: Prefix
            path: /
  defaultBackend:
    service:
      name: consumer
      port:
        number: 80
