POST http://localhost:3000/keyrotation
Content-Type: application/json

{
  "key": "person",
  "value": "Joao Carlos",
  "service": {
    "app": "consumer",
    "namespace": "default"
  }
}

###
GET http://127.0.0.1:3000/keyrotation
Content-Type: application/json

###
GET http://127.0.0.1/
Accept: application/json

###

GET http://127.0.0.1/healthcheck
Accept: application/json
